### ISSUE TITLE
Translate all issues to english

### ISSUE THREAD

**Issue by arthurbdiniz** [SIGS-UnB/core#161]
## Problem description
Lots of issues in Portuguese

## Expected Behavior
All issues in english

**Comment by toshitapandey** [comment]
@arthurbdiniz I want to pick this up. Is that ok?

**Comment by arthurbdiniz** [comment]
> @arthurbdiniz I want to pick this up. Is that ok?

Nice @toshitapandey, if you want you can translate all issues and publish as a comment here. Then i change on the repository!

**Comment by toshitapandey** [comment]
@arthurbdiniz Following are all the open issues translated to English. 
Please note that I have added images/links to the translated issues, so you can directly copy paste the issues to their respective links. 

# **Issue - https://github.com/SIGS-UnB/core/issues/1**
Refactor methods in Allocation Controller
 
## Problem description
Make_cell method too large, needs method extraction
rubocop being suppressed before the method

## Expected behavior
data allocation separate from make_cell
do not delete rubocop

## Current Behavior
make_cell does the data allocation after several other operations

# **Issue - https://github.com/SIGS-UnB/core/issues/2**
Add filters to Classes

## Problem description
The classes are presented together. Filtering them according to their allocation would facilitate the search.

## Expected behavior
There should be filters for the class allocation status.

## Current Behavior
There are no filters.

## Screenshots
![image](https://user-images.githubusercontent.com/26290053/45053998-057a8800-b062-11e8-879e-8651310f578b.png)

# **Issue - https://github.com/SIGS-UnB/core/issues/6**
Account Creation / Confirmation Email

## Problem description
User creating an account does not receive any email

## Expected behavior
Once the account is created, you will receive a welcome email

## Current Behavior
Account created without email

## Screenshots
![image](https://user-images.githubusercontent.com/18387694/45127306-0d175b00-b14e-11e8-9c2a-4a4bed83e0a3.png)

# **Issue - https://github.com/SIGS-UnB/core/issues/20**
Correction of parts of reports

## Problem description
The room reporting feature does not show the time occupied by each class

## Expected Behavior
### Case 1
> Generate report by room: Where will be shown the class and the busy schedules

### Case 2
> Generate report by discipline: It will be shown all the times and rooms that that discipline occupies

### Case 3
> Generate report by discipline: It will be shown all the times and rooms that that class occupies

### Case 4
> Generate report by Building: It will show the hourly grid of the whole building with the respective classes and schedules of each room

# **Issue - https://github.com/SIGS-UnB/core/issues/91**
Already in English

# **Issue - https://github.com/SIGS-UnB/core/issues/99**
List of possible improvements and implementations
* Login with LDAP
* [UFRN](https://docs.info.ufrn.br/doku.php)
* [ERLANGMS](https://github.com/erlangMS)

# **Issue - https://github.com/SIGS-UnB/core/issues/109**
Already in English

# **Issue - https://github.com/SIGS-UnB/core/issues/110**
Already in English

# **Issue - https://github.com/SIGS-UnB/core/issues/136**
Apply DIP for rooms report generation

## Problem description
Reporting by room is being performed within a single method.

## Expected Behavior
The report can be generated, without the high class needing to know the implementation of the classes that will generate the report pages.

## Current Behavior
## Possible Solution
Apply the dependency inversion principle to generate single page and single page reports (MultiplePage)

# **Issue - https://github.com/SIGS-UnB/core/issues/143**
Simplify action buttons within the class list

## Problem description
Actions then taking up a lot of space within the


![image](https://user-images.githubusercontent.com/18387694/49346436-a1c02500-f679-11e8-9981-25db7aa932ed.png)
## Expected Behavior
Make each

have at the end a button where you open a list of actions that can be performed as well as in the list of rooms
![image](https://user-images.githubusercontent.com/18387694/49346440-b8ff1280-f679-11e8-9247-b14c03b46922.png)
![image](https://user-images.githubusercontent.com/18387694/49346453-e64bc080-f679-11e8-8594-35b29e164bd3.png)

# **Issue - https://github.com/SIGS-UnB/core/issues/144**
Button in rooms with redirection

## Problem description
When you try to edit or delete a room using the pop-up it redirects you into the room before clicking the button
**route: / rooms / index**

## Expected Behavior
When you click the radio button just show the popup with room options and if it does not run nothing continue showing the room list

## Possible Solution
Currently the click is occurring by **ul**, ie when any part of **ul** is clicked it redirects into the specified room. The idea would be to uncouple this click event from the room's radio button

## Step to Play (for _bugs_)
1. Go to **/ rooms / index**
2. Click any option button in any room
   ![image](https://user-images.githubusercontent.com/18387694/49346500-90c3e380-f67a-11e8-8c77-79c30f5e9e2a.png)
3. Watch the pop-up appear and then be redirected to the room screen

# **Issue - https://github.com/SIGS-UnB/core/issues/158**
Already in English

# **Issue - https://github.com/SIGS-UnB/core/issues/159**
Already in English

# **Issue - https://github.com/SIGS-UnB/core/issues/160**
Already in English

# **Issue - https://github.com/SIGS-UnB/core/issues/161**
Already in English

# **Issue - https://github.com/SIGS-UnB/core/issues/162**
Already in English

# **Issue - https://github.com/SIGS-UnB/core/issues/163**
Already in English

**Comment by arthurbdiniz** [comment]
Thanks @toshitapandey, i will begin to update the issues! 😄

**Comment by arthurbdiniz** [comment]
Just updated all issues with your translation! Closing this.
