### ISSUE TITLE
Translate Releases to english

### ISSUE THREAD

**Issue by sconetto** [SIGS-UnB/core#162]
## Problem description
The release text is in brazilian portuguese

## Expected Behavior
It should be in english

**Comment by toshitapandey** [comment]
@sconetto @arthurbdiniz Is it okay if I pick this one up?

**Comment by arthurbdiniz** [comment]
> Is it okay if I pick this one up?

Sure @toshitapandey !

**Comment by toshitapandey** [comment]
@arthurbdiniz Since, I do not have access to edit the releases, I have translated the release as follows: 

## [**SIGS 2.0**](https://github.com/SIGS-UnB/core/releases/tag/2.0)
Delivery of the new version of the SIGS system. Added new features, bug fixes, code fixes, new deploy format and other minor fixes. All can be viewed from their issues.

**Completed**  ✅

- Bug when deploy to docker hub #151 @sconetto
- Create environment docker-compose #148 @arthurbdiniz
- Implements watchtower on deploy #146 @arthurbdiniz
- Create task to feed the application with data from the MatriculaWeb API #140 @victorcmoura
- Remove CSV parser page #131 @victorcmoura and @arthurbdiniz
- Sidebar dont fit all screen #126 @arthurbdiniz
- Size of particles not occupying entire screen #142 @arthurbdiniz
- Refactor sidebar in modules #122 @arthurbdiniz
- Remove duplicated code #106 @sconetto #117 @RomeuCarvalhoAntunes
- Clean Code application in user_controller #154 @ hugomartins013
- SOLID principle application in request model and room_solicitation model #139 @hugomartins013


## [**Show Me The Code 2**](https://github.com/SIGS-UnB/core/releases/tag/1.3)

Added several new functionalities, all can be viewed from their issues.

### Additions
**Completed** ✅

- Seed rooms #96
- Restructure routes and views of authentication #93
- Dialog for User Editing #84
- Remove popup notifications #76
- Register SIGS Domain #86
- Update README #78 and #82 by: @trevlewis and @sconetto
- Upload profile image to users #34
- Password Strength Meter #73 by: @fer22f
- Improve login screen form #7
- Request Screen Refactoring #56
- Show no open requests message #62
- Footer hiding part of the contents of the tables #59
- Deploy Enhancement #63
- Prototype following web enrolment #46
- Error not deploy (sshpass) #70

## [**Show Me The Code 1**](https://github.com/SIGS-UnB/core/releases/tag/1.1)

Added several new functionalities, all can be viewed from their issues.

### Additions
**Completed** ✅

- Set up Test Reporter CC #49
- Removal of Vagrant Machine and Puppet #41
- Show room capacity #38
- Database starting after Rails #31
- Save all keys in a file with gpg #30
- Refactor navbar #28
- Separate view from navbar and footer from application layer #24
- Wrong name Screen new users #22
- Separate prototype from project #17
- Reconfigure CI / CD Tools #12
- Update templates and add documentation #9
- Update version of Gems #8
- Separate docker-compose #4
- Continuous Deploy #52
- Separate building by campus #37
- Improve user experience with room filter #55
- Time indicator in the allocations table should be more intuitive #13

## [**Release 2**](https://github.com/SIGS-UnB/core/releases/tag/0.2.0)

In this version, the software has the following functionalities:

- Room Allocation
- Request Room Allocation
- Allow Allocations
- Generate API
- Generate Reports
- Generate Rooms and Class

## [**Release 1**](https://github.com/SIGS-UnB/core/releases/tag/0.1.0)
In this version, the software has the following functionalities:

- Manage User
- Keep Session
- Request Registration
- Approve Registration

**Comment by sconetto** [comment]
@toshitapandey seems good to me, what do you think @arthurbdiniz ?

**Comment by arthurbdiniz** [comment]
@toshitapandey, that really good! I have just updated all tags. Thanks for your time! 😄
